### PR TITLE
Features/csvimport

### PR DESCRIPTION
**Pull request by gplssm**
Remaining TODOs before merge

- [x] Move code to file 'import_data.py'
- [x] Provide function `import_ding0_from_csv()` as alternative to `import_from_ding0()`
- [x] Convert all hard-coded data and execution statements in `import_grids.py` to arguments of  `import_ding0_from_csv()`, i.e. file names can be provided as dict or a single path specification with a certain filename convention
- [x] Adapt code to restructured classes
- [x] Make .pkl grids running that run in dev branch #140 
- [ ] Create minimal example files and add to examples/examples_data
- [ ] Include in package data
- [ ] Document new feature: docstring including code example, static documentation
- [ ] Add to "What's new" for desired version
- [x] Include weather_cell_id in respective tables
- [ ] Verify correct functionality by comparing resulting grid imported from (a) .pkl and (b) .csv

### CODE REVIEW

**Comment by gplssm** [comment]
Regarding the documentation of the exported/imported tables, I would like to have them documented in a tabular way. One table for each CSV table that is exported would be nice. These tables for example can look like

Field | Description | Unit
-------| ---------------| -----
MV grid ID | Unique identifier | - 

For inspiration you can consult the [PyPSA components docs](https://pypsa.org/doc/components.html).

The documenting tables should be located in the static part of Ding0's docs. Just add a new section "CSV file export" to [this file](https://github.com/openego/ding0/blob/a46a76f296319406313e400a5b4ce065db96bbde/doc/usage_details.rst) and create the tables there.
[The sphinx documentation](http://www.sphinx-doc.org/en/master/markup/misc.html?highlight=csv#tables) describes the .rst markup language that is used in the documentation of our Python projects. For efficient creation of these tables, I recommend to use [csv-table](http://docutils.sourceforge.net/docs/ref/rst/directives.html#csv-table).

**Comment by birgits** [comment]
I merged the dev and also did some clean up and added the csv import option to the EDisGo class. @boltbeard please check if the csv import works. I didn't have any test files to do it myself.
Some things I noticed:
* circuit breakers are not considered yet
* csv import functions should be documented, at least the import_from_csv() function
* it should somewhere be documented what csv files are expected and how they need to look like

**Comment by birgits** [comment]
Oh, one more thing - import_from_ding0() assumes a string or ding0.core.NetworkDing0. Was ding0.core.NetworkDing0 renamed to ding0.core.GridDing0? Cause I couldn't find it anywhere. I already changed that in the EDisGo class but not in the import function.

**Comment by boltbeard** [comment]
The Current state of this is that the CSV import works to provide the same grid extension costs for one example of Ding0 grid 76. More Bug fixing needs to be done as mentioned on [issue 128](https://github.com/openego/eDisGo/issues/128)

 i.e. also if the oedb importer is built with the same import routines as the csv then this would also work

**Comment by birgits** [comment]
Obsolete

**Pull request closed without merging**
