### PR TITLE
Features/#261 emob tests

### LINKED ISSUE #261: Add more EMob Tests
At the moment the tests for SimBEV and TracBEV are very basic. We should add some more for the different options provided for the functions.

### PR DESCRIPTION
**Pull request by maike93he**
# Description
Added more EMob tests and restructured EMob tests so that functions/methods are tested within the correct module

Fixes #261 #275

# Checklist:

- [x] New and adjusted code is formatted using the `pre-commit` hooks
- [ ] New and adjusted code includes type hinting now
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by birgits** [comment]
Thanks @maike93he for your work!! I have a few remarks:

- [ ] The new test grid 4 should completely replace test grids 2 and 3, so these should be deleted and test grid 4 should become test grid 2. Before deleting test grids 2 and 3 all tests and examples using those grids should be adapted to use test grid 4. I saw that you already did that in some cases but I am not sure if there are other places where it needs to be adapted.
- [ ] The new simbev and tracbev data should completely replace the old data. Same as above applies.
- [ ] The new simbev and tracbev data is quite large. I would prefer having smaller data.
- [ ] In the jupyter notebooks all used data should be downloaded from github or some other online source. The reason for that is, that external people using eDisGo will usually install it from PyPI. The examples and test data are in that case not in the edisgo directory. The example should therefore offer an automatic download of the data needed. I already adapted it for the grid data but not yet for simbev and tracbev data. 
- [ ] One of the tests is failing for python 3.7. Could you please have a look at it?

Two minor remarks:
- [ ] Please always create paths using Path() or os.path.join() or something similar and don't hard-code the directory separator, as Windows and Linux use different separators. I already changed that in the notebook.
- [ ] Also, please don't upload executed notebooks but always clear output before committing, otherwise it is hard to see changes made to the actual content of the notebook.

**Comment by birgits** [comment]
@maike93he is there a better way to download simbev data in electromobility notebook? Listing all filenames takes up alot of space..

**Comment by birgits** [comment]
All SimBEV and TracBEV test data was removed, was that intended @maike93he?

**Comment by maike93he** [comment]
> @maike93he is there a better way to download simbev data in electromobility notebook? Listing all filenames takes up alot of space..

There probably is, I am still working on it.

**Comment by maike93he** [comment]
> All SimBEV and TracBEV test data was removed, was that intended @maike93he?

No, it wasn't. On my local branch the data is still there. I only removed the "old" test data (ding0 grid 2 and 3, tracbev and simbev data and replaced it with dingo grid 4 and tracbev 2 and simbev 2 data).

**Pull request merged**
