### PR TITLE
Calrified and simplified installation on windows

### PR DESCRIPTION
**Pull request by khelfen**
* Rewrote installation guide
* Refactored environment yaml for conda users
    * added one for the installation of dev env
* Fixed a bug due to changes in in recent contextily versions which prevented plotting of background maps

### CODE REVIEW

**Comment by khelfen** [comment]
@AnyaHe could you please check the installation guide for both the [standard installation](https://github.com/openego/eDisGo/blob/feature/windows-installation-description/doc/quickstart.rst) and the [dev installation](https://github.com/openego/eDisGo/blob/feature/windows-installation-description/doc/dev_notes.rst) for windows (using [this branch](https://github.com/openego/eDisGo/tree/feature/windows-installation-description) and merge the PR if everything works fine?

**Comment by AnyaHe** [comment]
Hi,
sorry for the late reaction.
So, when I install the normal environment, I get the following error:
ModuleNotFoundError: No module named 'plotly'

**Comment by AnyaHe** [comment]
For the dev-environment, I received a different error when running the example file: 
ModuleNotFoundError: No module named 'egoio'

**Comment by khelfen** [comment]
> Hi, sorry for the late reaction. So, when I install the normal environment, I get the following error: ModuleNotFoundError: No module named 'plotly'

This is expected as this installs the edisgo base installation

https://github.com/openego/eDisGo/blob/f58d1a2eac71f79ddf56f5372fdd6dae81b6d628/eDisGo_env.yml#L19-L20

and `plotly` is only installed when installing the `geoplot`, `examples` or `full` edisgo version.

https://github.com/openego/eDisGo/blob/f58d1a2eac71f79ddf56f5372fdd6dae81b6d628/setup.py#L57-L63

Do you think I should change it to `edisgo[full]` within the yaml?

**Comment by AnyaHe** [comment]
I am not sure. I would at least provide an example-file that works with the described installation. Or add an optional install to the description where you can install the full version. How would one proceed if he or she wanted to have the full installation? I did not see that in the description.

**Comment by khelfen** [comment]
You can find that within the [quickstart](https://github.com/openego/eDisGo/blob/feature/windows-installation-description/doc/quickstart.rst). I'll add a line which links to that.

**Comment by khelfen** [comment]
Also at the moment I can't provide a dev example which works with the PyPI `v0.1.0` on the heat pump integration or dev branch. Please `checkout` to the master branch and run the tests there if using the PyPI version. The non-dev yml is only to provide a service to make the PyPI package installable for windows users.

**Comment by khelfen** [comment]
> For the dev-environment, I received a different error when running the example file: ModuleNotFoundError: No module named 'egoio'

I can't reproduce this on my windows machine 🤔 `egoio` should have been installed with the `pip install -e .[full]` command

https://github.com/openego/eDisGo/blob/f58d1a2eac71f79ddf56f5372fdd6dae81b6d628/eDisGo_env_dev.yml#L19-L20

**Review by AnyaHe — APPROVED** [review]
Looks good, thank you for cleaning that up! :)

You could consider adding pypsa and pyomo to the conda-forge, but I am not sure if it is better to have more packages in the conda-forge declaration or to keep it slim.

**Comment by AnyaHe** [comment]
> Also at the moment I can't provide a dev example which works with the PyPI `v0.1.0` on the heat pump integration or dev branch. Please `checkout` to the master branch and run the tests there if using the PyPI version. The non-dev yml is only to provide a service to make the PyPI package installable for windows users.

Note that some tests are still failing. We hope that will resolve with an update of the PyPI version to the current status.

**Pull request merged**
